### ISSUE TITLE
No Module named itkHelpers

### ISSUE THREAD

**Issue by buaaduke** [InsightSoftwareConsortium/ITKPythonPackage#128]
i install itk-v5.0rc2 and load a mesh file as follows，

import itk
meshReader = itk.MeshFileReader.New('bones.stl', itk.Mesh(itk.D, 3))

but get error like File "~/anaconda3/envs/py3t1/lib/python3.6/site-packages/itkTemplate.py", line 374, in __call__
    import itkHelpers
ModuleNotFoundError: No module named 'itkHelpers'

**Comment by fbudin69500** [comment]
Thanks for the report. I also stumbled upon this issue and I will submit a patch asap to solve it.

**Comment by buaaduke** [comment]
Thank you for your reply. I changed my code as follows,

meshType = itk.Mesh[itk.F, 3]
meshReader = itk.MeshFileReader[meshType].New()
meshReader.SetFileName('bunny.obj')
meshReader.Update()

then i get error Segmentation fault (core dumped), i also try  ITKIOMeshSTL to load stl mesh, but still get the same error. How can i load mesh file?

**Comment by fbudin69500** [comment]
Should be addressed by https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/130

**Comment by buaaduke** [comment]
Thank you for your help. I add itkHelpers to scripts/setup_py_configure.py in line 248. Then, i used the command 'python setup.py install' to install  ITKPythonPackage. The itkHelper module can be successfully  imported, but i can not use itk.MeshFileReader, how do i install itk mesh module?

**Comment by fbudin69500** [comment]
I had missing that second issue (Mesh) in your report. I will take a look at it today.

**Comment by fbudin69500** [comment]
For reference, the discussion about the `itk.MeshFileReader` issue is on the [ITK discourse forum](https://discourse.itk.org/t/trianglemeshtobinaryimagefilter-in-python/1604/12?u=fbudin) and an issue has been opened in the [ITK Github repository](https://github.com/InsightSoftwareConsortium/ITK/issues/866#event-2339854753).
