### ISSUE TITLE
circleci and travis tests failing for ITK remote modules

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITKPythonPackage#139]
I am updating the remote modules for ITK v5.1rc02. Each of their respective circleci and travis python package builds are failing. When I build circleici or travis with the master branch of any of the remote modules I get the following error:
![Screen Shot 2020-04-17 at 3 52 58 PM](https://user-images.githubusercontent.com/42974718/79613127-8ebdc180-80c3-11ea-9024-644ad2aef4a3.png)![Screen Shot 2020-04-17 at 2 17 25 PM](https://user-images.githubusercontent.com/42974718/79607952-c45dad00-80b9-11ea-947b-0d261640a6bd.png)

I have tried a variety of different changes, but none have worked. These include:

- declare `export ITK_PACKAGE_VERSION=v5.1rc02` before `./dockcross-manylinux-download-cache-and-build-module-wheels.sh`  or `./macpython-download-cache-and-build-module-wheels.sh`
- In setup.py set `install_requires = [ r'itk >= 5.1rc2]`
 
When I configure the python package for  ITKv5.0.1 they pass. What is even more puzzling is the circleci package build (building linux python packages) worked when the first set of changes for ITK v5.1rc02 were merged on March 1st. 

I have been doing tests through my forked repository [ITKAnisotropicDiffusionLBR](https://github.com/mseng10/ITKAnisotropicDiffusionLBR.git) (master). This includes all the changes up until this point. I am unsure if the problem is due to the remote modules or the ITKPythonPackage, hence the issue. Any information would be valuable.

**Comment by thewtex** [comment]
> v5.1rc02

@mseng10 could you please try v5.1rc03? Thanks!

@hjmjohnson

**Comment by mseng10** [comment]
@thewtex I got the same issue using v5.1rc03.

**Comment by SimonRit** [comment]
I think I have a similar issue on Azure pipelines with the RTK python package after changing the version of the ITKPythonPackage from 5.0.1 to 5.1rc3, see the build log [here](https://dev.azure.com/simonrit/RTK/_build/results?buildId=408&view=logs&jobId=eafb87dd-1923-5b11-0b2b-e4ed58eef8aa&j=eafb87dd-1923-5b11-0b2b-e4ed58eef8aa&t=c476e6ed-da0f-5921-29b4-af92b6bde1f3).

**Comment by thewtex** [comment]
@mseng10 @SimonRit this will be addressed by #141 in 5.1.0.

**Comment by mseng10** [comment]
@thewtex thank you for addressing this! Closing issue now.

**Comment by thewtex** [comment]
A new GitHub Actions configuration for ITK 5.1.0 remote module CI is added here:

  https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/82

We just copy the *{{ cookiecutter.project_name }}/.github/workflows/build-test-package.yml* to the remote module repository. Optionally, set `pypi_password` to be a PyPI API token for the package, and the packages will be uploaded the next time the repository is tagged.
