### ISSUE TITLE
import _ITKPyBasePython failed

### ISSUE THREAD

**Issue by xiaoxifei1223** [InsightSoftwareConsortium/ITKPythonPackage#143]
my Env:
win10 64 bits
python 3.6
itk 5.1.0

my err:
 File "C:\Users\haoch\AppData\Local\Programs\Python\Python36\lib\site-packages\itk\Configuration\..\ITKPyBasePython.py", line 15, in <module>
    import _ITKPyBasePython
ImportError: DLL load failed:

when I use itk.imread(path),then the error occured
what can I do?

**Comment by thewtex** [comment]
Hello, I am working on a patch for this -- I will follow-up when it is ready to test.

**Comment by danarteaga** [comment]
Great - I have the same issue on Windows 10.

**Comment by thewtex** [comment]
@xiaoxifei1223 @danarteaga please install `5.1.0.post1` with:

```
python -m pip install --upgrade itk
```

and let us know how it goes.

**Comment by danarteaga** [comment]
Unfortunately, this is still giving me the same error. This error was not present when I downgraded to itk v5.0.1.

**Comment by xiaoxifei1223** [comment]
Thanks everyone, when I use itk v 5.0.0, the error don`t occure.

**Comment by danarteaga** [comment]
Just to clarify, I am still getting the error with 'itk==5.1.0.post1'

**Comment by thewtex** [comment]
@danarteaga thanks for testing and the feedback. An update has been posted `5.1.0.post2`. @xiaoxifei1223 @danarteaga please install `5.1.0.post2` with:

```
python -m pip install --upgrade itk
```

and let us know how it goes.

**Comment by danarteaga** [comment]
It works now, thanks!
