### ISSUE TITLE
Automatic upload of nightly release

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITKPythonPackage#15]
Assuming GITHUB_TOKEN is set, doing the following on each build bot (linux, macosx, windows) should automatically upload the nightly releases:

```
pip install scikit-ci-addons==0.12.0

cd ITKPythonPackage

project="InsightSoftwareConsortium/ITKPythonPackage"

commit_date=$(git log -1 --format="%ad" --date=local | date +%Y%m%d)

platform=$(ci_addons publish_github_release $project --display-python-wheel-platform)

ci_addons publish_github_release $project \
    --release-packages "dist/*" \
    --prerelease-packages dist/*.dev${commit_date}*${platform}*.whl \
    --prerelease-packages-clear-pattern "*${platform}*.whl" \
    --prerelease-packages-keep-pattern "*.dev${commit_date}*.whl"

```

More details here http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#use-case-automatic-creation-of-nightly-prerelease-from-different-build-machines

Cc: @thewtex

**Comment by thewtex** [comment]
@jcfr Thanks! Work in progress...

**Comment by jcfr** [comment]
Let me know if you started on this, if not I will move forward with it from my :bed: :+1:

**Comment by thewtex** [comment]
:+1:  I have started -- used it to upload the Linux wheels and sdist's!

OSX is next :-)

Make sure to get some :zzz:

**Comment by thewtex** [comment]
OSX :heavy_check_mark: 

Windows next :running_man:

**Comment by thewtex** [comment]
:heavy_check_mark: Windows!
