### ISSUE TITLE
Script failure in macOS Github CI

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#161]
## Overview

Failures in the [`Build Python Package` CI step](https://github.com/slicersalt/ITKShape/runs/2546694241?check_suite_focus=true) may be related to [macpython-build-common.sh](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blame/master/scripts/macpython-build-common.sh). 

## Details

The `Build Python Package` step of the `build-macos-python-package` CI check is failing in both [ITKModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/runs/2518884701) and the [ITKShape](https://github.com/slicersalt/ITKShape) external module. The script appears to experience a broken pipe issue when checking for the `ninja` dependency, tries to install `ninja`, and then fails to symlink due to file conflicts.

It looks like the dependency check was added recently to [macpython-build-common.sh](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blame/master/scripts/macpython-build-common.sh#L33-L40)
``` brew update
brew info doxygen | grep --quiet 'Not installed' && brew install doxygen
brew info ninja | grep --quiet 'Not installed' && brew install ninja
NINJA_EXECUTABLE=$(which ninja)
brew info cmake | grep --quiet 'Not installed' && brew install cmake
CMAKE_EXECUTABLE=$(which cmake)
```

We've previously installed Ninja in the `Get specific version of CMake, Ninja` step and I believe we expect to install python by invoking [macpython-install-python.sh](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/macpython-install-python.sh) rather than as a dependency with `brew install ninja`. 

We have seen successful builds more recently than the changes to `macpython-build-common.sh` so it's still possible that issues are unrelated or only indirectly related to these changes (see the most recent `build, test, package` build in [ITKModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/runs/2514925879?check_suite_focus=true)).

## Expected behavior
Need clarification. Do we expect to reinstall ninja in this step?

Expect no script errors.

## Observed behavior
>++ brew update
++ brew info doxygen
Already up-to-date.
++ grep --quiet 'Not installed'
Warning: Treating doxygen as a formula. For the cask, use homebrew/cask/doxygen
++ brew info ninja
++ grep --quiet 'Not installed'
Error: Broken pipe @ io_writev - <STDOUT>
++ brew install ninja
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.5
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:5d79eedf91642b87bd25e7b791b941ce9aad4735fecd1bc59c9c7faab50cbca6
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5d79eedf91642b87bd25e7b791b941ce9aad4735fecd1bc59c9c7faab50cbca6?se=2021-05-10T15%3A05%3A00Z&sig=YrqTp4iYFFZGIufk6gGaf5IfSXU4%2BYTHBj4ArwOc3Kc%3D&sp=r&spr=https&sr=b&sv=2019-12-12
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/manifests/1.10.2
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/blobs/sha256:5eb553057f7595f0c607b100ac263ab5834a057b11e8aca512555f5129f6d544
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5eb553057f7595f0c607b100ac263ab5834a057b11e8aca512555f5129f6d544?se=2021-05-10T15%3A05%3A00Z&sig=QE%2B%2BkPATpABW9tGUloQO2QT%2Bq2LVcFQ7wPraBbmyfzU%3D&sp=r&spr=https&sr=b&sv=2019-12-12
==> Installing dependencies for ninja: python@3.9
==> Installing ninja dependency: python@3.9
==> Pouring python@3.9--3.9.5.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

## Other Comments/Questions
- Adding the issue here because it seems related to [macpython-build-common.sh](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blame/master/scripts/macpython-build-common.sh). Should I move it to [ITKModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate) instead?
- How do we determine which Python version(s) to install in the CI container environment?
- Taking a look at the [Ninja repo](https://github.com/ninja-build/ninja), it doesn't seem that any additional installation behavior was added during the timeframe in which we started to see this issue, but its [Homebrew page](https://formulae.brew.sh/formula/ninja) does list Python@3.9 as a dependency. Why does the last passing build install Python 3.8 as the Ninja dependency instead?
- Downgrading ITK to `v5.2.0` from `v5.2.0.post2` seems to return passing CI checks, but I'm unclear as to how or why the ITK build version would determine how we interact with Ninja.

**Comment by tbirdso** [comment]
@thewtex Here's the issue I mentioned earlier - has implications for both `ITKShape` and `ITKModuleTemplate`.

**Comment by thewtex** [comment]
@tbirdso thank you so much for the detailed write-up and description! This is very helpful.

Addressed with https://github.com/InsightSoftwareConsortium/ITKPythonPackage/commit/36e36bb01dac03abad5b70dc35bd8b7aebd68fab and verified with both `ITKShape` and `ITKModuleTemplate`.

**Comment by thewtex** [comment]
> How do we determine which Python version(s) to install in the CI container environment?

We install all python.org CPython versions that we support -- for ITK 5.2 this is 3.6, 3.7, 3.8, 3.9. ITK 5.3 will drop 3.6, add 3.10.

> Taking a look at the Ninja repo, it doesn't seem that any additional installation behavior was added during the timeframe in which we started to see this issue, but its Homebrew page does list Python@3.9 as a dependency. Why does the last passing build install Python 3.8 as the Ninja dependency instead?

If they are binary packages, this may be a bug in the Homebrew build configuration -- Python is only required to help build the `ninja` binary.

> Downgrading ITK to v5.2.0 from v5.2.0.post2 seems to return passing CI checks, but I'm unclear as to how or why the ITK build version would determine how we interact with Ninja.

`itk-5.2.0.post2` contains fixes for ARM, which is why we needed to handle ninja differently.
