### ISSUE TITLE
Upgrade Docker image CMake version

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#191]
Warnings from Python external module CI show that CMake version is too low:
```
-- Detecting CXX compile features - done
CMake Warning at C:/P/IPP/ITK-source/ITK/CMake/ITKModuleExternal.cmake:12 (message):
-- cmake_minimum_required of 3.10.2 is not enough.
  cmake_minimum_required must be at least 3.16.3
-- This is needed to allow proper setting of CMAKE_MSVC_RUNTIME_LIBRARY.
Call Stack (most recent call first):
-- Do not be surprised if you run into link errors of the style:
  error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_Static' doesn't match value 'MDd_Dynamic' in module.obj
  CMakeLists.txt:9 (include)
```

This is confirmed by manually downloading the image and running `cmake --version` in a bash shell.

CMake version should be upgraded to at least the ITK minimum (3.16.3) and preferably the maximum for future proofing (3.19).

**Comment by thewtex** [comment]
> P/IPP/ITK-source

This appears to be Windows instead of a Linux Docker image? Was CMake 3.10.2 installed on the local system?

**Comment by tbirdso** [comment]
You are right, after encountering this warning a couple more times I now believe the source is the `cmake_minimum_required` line in each given external module rather than the Docker CMake version.

See [https://github.com/InsightSoftwareConsortium/ITKSplitComponents/blob/master/CMakeLists.txt#L1](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/blob/master/CMakeLists.txt#L1):
```
cmake_minimum_required(VERSION 3.10.2)
project(SplitComponents)
```

Will close this issue in favor of a more specific issue in ITKSplitComponents.
