### ISSUE TITLE
Upgrade zstd version for Linux packaging

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#192]
`zstd` is currently [fetched from data.kitware.com](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh#L40) for Linux builds and is out of date at v1.2.0 < v1.5.2. Either 1) zstd should be updated on data.kitware.com or 2) zstd should be pulled from an up-to-date source.

With this change the `--long=31` flag should be enabled to improve archive compression as is currently done on macOS.

**Comment by thewtex** [comment]
Closed via #225
