### ISSUE TITLE
Investigate is zip_safe should be disabled

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITKPythonPackage#20]
Please see SimpleITK/SimpleITKPythonPackage@bdc00b98380e082c0c166efb36d7050bc0854ff9 for details.

**Comment by thewtex** [comment]
Thanks for the note. I'll try to reproduce with ITK, then investigate enabling the option by default in skbuild.

CC: @jcfr

**Comment by thewtex** [comment]
The result of building ITK with `python setup.py install`:

```
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import itk
>>> image = itk.Image[itk.UC, 2].New()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  AttributeError: 'module' object has no attribute 'Image'
```

**Comment by thewtex** [comment]
This error persists even after adding `zip_safe=False` -- it may point to a different issue.

**Comment by thewtex** [comment]
We now use scikit-build-core / pyproject.toml.
