### ISSUE TITLE
Failure to build remote module wheels for Github `macos-12` runner

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#201]
## Overview

Many ITK remote modules previously depended on the `macos-10.15` Github Actions CI runner which has now been deprecated ([blog post](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/)). Failures have been observed in updating to `macos-12` with a new XCode version.

### Workaround

For now remote modules can update to `macos-11` for which `/Applications/Xcode_11.7.app` is still available. It is reasonable to believe that at some point in the (not-so-near) future `macos-11` will also be deprecated.

### Expected behavior

ITK remote module Python wheels build without warnings or errors.

### Observed behavior

With a `macos-12` runner and selecting a newer XCode version, i.e.
```
sudo xcode-select -s "/Applications/Xcode_14.0.app"
```

An error such as below is observed:
```
ninja: error: '/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework', needed by '/Users/svc-dashboard/D/P/ITKPythonPackage/ITK-3.10-macosx_x86_64/Wrapping/Generators/Python/itk/_SplitComponentsPython.so', missing and no known rule to make it
```

Reproduced in both ITKSplitComponents and ITKCLEsperanto external modules. There are no clear references to XCode 11.7 in either module or ITKPythonPackage to cause this error. May require updating the ITK build process for a newer XCode.

cc @thewtex

**Comment by thewtex** [comment]
@tbirdso yes, we will need to update the XCode SDK version used for the ITKPythonPackages.

**Comment by thewtex** [comment]
The itk-5.3rc4.post3 builds were built against /Applications/Xcode_13.2.1.app, which [is the default](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md) on the GitHub Action Runner `macos-11` image.
