### ISSUE TITLE
Allow building module wheels for arm64 linux

### ISSUE THREAD

**Issue by mdevl** [InsightSoftwareConsortium/ITKPythonPackage#207]
Currently the script `dockcross-manylinux-download-cache-and-build-module-wheels.sh` only allows to build x86 python wheels. To my understanding it should be possible  to also build wheels of a python ITK module for arm64 architecture on a linux machine.

Modifying the user-facing script to allow specifying an architecture different from x86 would be very helpful and greatly appreciated.

**Comment by tbirdso** [comment]
cc @jcfr @thewtex

**Comment by thewtex** [comment]
Closed via #228
