### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET ignored

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKPythonPackage#209]
https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/cbb10fa729d89252f918668c9c9801a3057d6cd3/scripts/macpython-build-module-wheels.sh#L71 and https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/cbb10fa729d89252f918668c9c9801a3057d6cd3/scripts/macpython-build-wheels.sh#L147 specify `CMAKE_OSX_DEPLOYMENT_TARGET`, thus effectively ignoring environment variable `MACOSX_DEPLOYMENT_TARGET` specified by CI script in the [module template](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/blob/f4cd0289406cc2f0348441bd3670d95173f6ef16/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/build-test-package.yml#L198) and in modules derived from it. If this is different from the default, as in https://github.com/dzenanz/ITKIOOMEZarrNGFF/blob/697b25163b6e0423865d1e67288bb43761a04707/.github/workflows/build-test-package.yml#L202 then that value is ignored. If `MACOSX_DEPLOYMENT_TARGET` environment variable is specified, it should be respected.

**Comment by thewtex** [comment]
@dzenanz could you please create a patch that sets `osx_target` to `MACOSX_DEPLOYMENT_TARGET` if `MACOSX_DEPLOYMENT_TARGET` is set?
