### ISSUE TITLE
Failed to compile module with v5.3rc04.post4

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITKPythonPackage#223]
The recently released RTK packages are already obsolete with the new 5.3rc4.post4 ITK packages. However, when I try to upgrade, the CI to [post4 ITK Python builds](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post4), I have a [new error at link time](https://github.com/SimonRit/RTK/actions/runs/3469976218/jobs/5797612010#step:6:825). I have no idea what could explain this new issue. Has anyone else tried to build module packages with this new ITK RC release?

**Comment by SimonRit** [comment]
The same issue is being addressed in InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#9 (cc @tbirdso @LucasGandel).

**Comment by tbirdso** [comment]
Hi @SimonRit, yes, good catch. ITK Windows build archives for v5.3rc04.post4 are generated with VS22 rather than VS19 as before. Due to a change in MSVC it is required that ITK modules for v5.3rc04.post4 must also be built with VS22.

**Comment by SimonRit** [comment]
See fix in InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#9
