### ISSUE TITLE
Build breaks in TBB

### ISSUE THREAD

**Issue by yurivict** [InsightSoftwareConsortium/ITKPythonPackage#226]
```
/disk-samsung/freebsd-ports/science/py-itk/work-py39/ITKPythonPackage-5.3rc04.post3/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/oneTBB-prefix/src/oneTBB/src/tbb/arena.cpp:235:19: error: variable 'drained' set but not used [-Werror,-Wunused-but-set-variable]
    std::intptr_t drained = 0;
                  ^
1 error generated.
```

The oneTBB distribution uses ```-Werror``` with the code that has at least one C++ warning which makes it broken. Are you able to build it?

Why download and build oneTBB when it exists in packages? How can I use an existing package instead?

Version: 5.3rc04.post3
clang-14
FreeBSD 13.1

**Comment by dzenanz** [comment]
I don't think I ever built TBB myself. @thewtex might know why you need to build it, but I assume that's because Intel didn't build it themselves for your platform (OS+ISA).

**Comment by thewtex** [comment]
> The oneTBB distribution uses -Werror with the code that has at least one C++ warning which makes it broken. Are you able to build it?

Yes, oneTBB is sensitive to compilers / platforms.

> Why download and build oneTBB when it exists in packages? How can I use an existing package instead?

@yurivict this repository contains the configuration for building the wheel packages distributed on pypi.org. If the goal is to build / install for a system installation, the wrapping can just be built from the `ITK` repository with `ITK_WRAP_PYTHON` `ON`.
