### ISSUE TITLE
Add ITKPythonPackage update step in download scripts

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#232]
ITKPythonBuilds archives are distributed with a git tree for ITKPythonPackage to 1) indicate what build scripts were used in creating the packaged build artifacts and 2) provide easy access to scripts for building module wheels using the packaged artifacts. However, it is often the case that ITKPythonPackage scripts must be patched following ITKPythonBuilds releases.

Following from initial investigation in https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/13, `download` scripts should be updated to include a step in which decompressed ITKPythonBuilds archives can be updated to a version of ITKPythonPackage scripts set by the user.

**Comment by dzenanz** [comment]
This needed for CI in https://github.com/dzenanz/ITKIOOMEZarrNGFF. The old version of Linux build script references the old version of dockcross, resulting in [build failure](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3574958461/jobs/6010884071). As you assigned this to yourself, I will keep an eye on the progress 😄

**Comment by tbirdso** [comment]
Thanks for the heads up @dzenanz , aiming to have a PR up today
