### ISSUE TITLE
Wheels are empty

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKPythonPackage#261]
When it comes to make the wheel contents on the `release` branch for v5.4rc02, CMake is spitting out warnings about empty variables related to the `ITK_MODULE_*_GROUP` variables.

It is likely that this code has issues:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/4936bcc431f3268270d3edf176648a86a28f59cd/cmake/ITKPythonPackage.cmake#L34-L35

That was similarly addressed in:

https://github.com/InsightSoftwareConsortium/ITK/commit/6384cd067ae957ef61d21b25f92df44360c6b990

CC @jcfr

**Comment by jcfr** [comment]
Since the macro `ipp_set_itk_groups` does not seem to be used, the issue is likely somewhere else.

**Comment by jcfr** [comment]
Problematic code is likely this one:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/4936bcc431f3268270d3edf176648a86a28f59cd/CMakeLists.txt#L438-L449

**Comment by jcfr** [comment]
Regression was introduced in InsightSoftwareConsortium/ITK@efa749515db840b54f7329b261d3ec4c3a575f83 as it broke the assumption that the module name was on the same line as the `itk_module` call.
