### ISSUE TITLE
Using `cache` in `travis`

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITKPythonPackage#61]
Hi, I am facing timeouts in a [external module](https://github.com/phcerdan/ITKIsotropicWavelets/blob/master/.travis.yml) in `travis` with the `macos` script: [macpython-download-cache-and-build-module-wheels.sh](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/macpython-download-cache-and-build-module-wheels.sh)

Do you have experience with [travis caching](https://docs.travis-ci.com/user/caching/)? I wonder if there is a way to take advantage of it for this.

**Comment by thewtex** [comment]
Yes, we should add travis caching support for the downloaded ITK build archive.

**Comment by thewtex** [comment]
Looking into the [travis caching documentation](https://docs.travis-ci.com/user/caching/#Things-not-to-cache), it states

> The cache’s purpose is to make installing language-specific dependencies easy and fast, so everything related to tools like Bundler, pip, Composer, npm, Gradle, Maven, is what should go into the cache.
>
> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source:
>
> Android SDKs
> Debian packages
> JDK packages
> Compiled binaries
> Docker images

So, caching is not recommended for the binary downloads.

However, the builds speed is improved by #62
