### ISSUE TITLE
Option to only build specific python versions (2.7 and 3.6)

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITKPythonPackage#66]
Hi, I am facing timeouts in `travis` with the external module ITKIsotropicWavelets, config file: [.travis.yml](https://github.com/phcerdan/ITKIsotropicWavelets/blob/master/.travis.yml) and travis [webpage](https://travis-ci.org/phcerdan/ITKIsotropicWavelets) of the module.

Is there an option to not build the wrapping for python 3.4, and 3.5 that I can tweak from `.travis.yml`?

**Comment by thewtex** [comment]
@phcerdan Good idea. Please take a look at #69
