### ISSUE TITLE
Add option to download nightly build or latest release

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITKPythonPackage#70]
In the [download-cache-and-build scripts](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/macpython-download-cache-and-build-module-wheels.sh#L7) there is a hardcoded path to the [tag](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/tags) to download.  Would it be possible for the user to change this tag to [latest](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/releases/tag/latest) instead?

I guess not super important, but some kind of variable holding the version to download might help when you need to change the tag for a new release.

**Comment by phcerdan** [comment]
Sorry, maybe I am confused and this is not the root of the issue. The problem I am facing is that `travis` seems to ignore latest changes in this repository (basically not building 3.4 as introduced by #69 ). I have deleted the cache in `travis`, but still building it.

**Comment by fbudin69500** [comment]
@thewtex and @jcfr : Any idea?

**Comment by thewtex** [comment]
@phcerdan good idea. #72 could enable this.
