### ISSUE TITLE
LabelObject Pixel type none works

### ISSUE THREAD

**Issue by benjaminhon** [InsightSoftwareConsortium/ITKPythonPackage#71]
Hi,
I don't seem to be able to get the right pixel type for creating a LabelObjectType using the python wrappers. I am trying to convert from the C++ code. here

https://itk.org/ITKExamples/src/Filtering/ImageFusion/OverlayLabelMapOnTopOfAnImage/Documentation.html

```
Dimension = 3
PixelType = itk.UC

LabelType = itk.UC
LabelObjectType = itk.LabelObject[LabelType, Dimension]
LabelMapType = itk.LabelMap[PixelType, Dimension]
```

I keep getting this error

```
KeyError: 'itkTemplate : No template (<itkCType unsigned char>, 3) for the itk::LabelObject class'
```

I tried other types but all seem to not be supported, 

Can anyone help? thanks

**Comment by fbudin69500** [comment]
Hi,

See[ my answer to your question on the ITK Discourse forum](https://discourse.itk.org/t/using-labelmap-in-python/259).
Thanks!
Francois

**Comment by benjaminhon** [comment]
Thanks much appreciated!
