### ISSUE TITLE
ppc64le with Python 3.(5/6)

### ISSUE THREAD

**Issue by dgvigil** [InsightSoftwareConsortium/ITKPythonPackage#98]
In the releases there is a wheel available for ppc64le with python 2. Can one please be generated for either Python 3.5 or Python 3.6?  Either would be helpful.

**Comment by thewtex** [comment]
@dgvigil [Here](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/releases/download/v4.13.0/itk-4.13.0-cp36-cp36m-linux_ppc64le.whl) is a wheel for Python 3.6. Please download it and install with

```
python -m pip /path/to/itk-4.13.0-cp36-cp36m-linux_ppc64le.whl
```

and let me know if it works for you.

Thanks!

**Comment by dgvigil** [comment]
That worked. Thank you.

    python -m pip install itk-4.13.0-cp36-cp36m-linux_ppc64le.whl
    Processing ./itk-4.13.0-cp36-cp36m-linux_ppc64le.whl
    Installing collected packages: itk
    Successfully installed itk-4.13.0

**Comment by regiscely** [comment]
Thank you for the ppc64le package availability but do you have ppc64le whl for version 5.0.0 ?

**Comment by thewtex** [comment]
@regiscely we need to resolve this issue: https://github.com/InsightSoftwareConsortium/ITK/issues/1078
